spring:
  application:
    name: spring-ref-id-employe
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/employeeDb?useSSL=true&useJDBCCompliantTimezoneShift=TRUE&useLegacyDatetimeCode=FALSE&serverTimezone=UTC
    password: admin
server:
  port: 8083