spring:
  application:
    name: spring-ref-id-employe
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/employedb
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8083